spring:
  profiles:
    active: -dev

---
#生产配置
spring:
  profiles: dev
  application:
    name: cloud-config-dev

---
#测试配置
spring:
  profiles: test
  application:
    name: cloud-config-test


---
#服务端口
server:
  port: 8001
mybatis:
  type-aliases-package: entity
  #?mapper.xml的路径
  mapper-locations: classpath:/mapper/*.xml
  #配置单个文件的最大
spring:
  profiles:
    active: 8001
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      ##jdbc:mysql://localhost:3306/reds?characterEncoding=UTF-8
      url: jdbc:mysql://localhost:3306/reds?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password:
  cache:
    ehcache:
      config: classpath:/ehcache.xml
  application:
    #应用程序名称
    name: cloud-provider-goods

  cloud:
    consul:
      #注册中心的配置
      host: localhost
      port: 8500
      discovery:
        #主机名称
        hostname: 127.0.0.1
        #对外暴露的服务名称
        service-name: ${spring.application.name}
        #是否注册
        register: true
        
---
#服务端口
server:
  port: 9001

spring:
  profiles:
    active: 9001
  application:
    name: cloud-book-trade
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        register: true

#指定商品微服务负载均衡的策略采用的是随机
cloud-provider-goods:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
   NFLoadBalancerRuleClassName: xg.myRule.MyRule
   ConnectTimeout: 250    #请求连接的超时时间
   ReadTimeout: 1000       #请求处理的超时时间
   OkToRetryOnAllOperations: true    #对所有操作请求都进行重试
   MaxAutoRetriesNextServer: 1    #切换实例的重试次数
   MaxAutoRetries: 1              #对当前实例的重试次数




